#cloud-config
package_update: true
package_upgrade: true

packages:
  - nginx

ssh_pwauth: false
disable_root: true

ssh_keys:
  ed25519_private: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz
    c2gtZWQyNTUxOQAAACA658EWb8Dos+6QKN4NhjdYVbTFCpxHVlYRJAUTo+EWbAAA
    AIiGVH9shlR/bAAAAAtzc2gtZWQyNTUxOQAAACA658EWb8Dos+6QKN4NhjdYVbTF
    CpxHVlYRJAUTo+EWbAAAAEDFtlszWZkhmDff3lPhkihizwRv+k8vsxCwnGJpnQMd
    FjrnwRZvwOiz7pAo3g2GN1hVtMUKnEdWVhEkBROj4RZsAAAAAAECAwQF
    -----END OPENSSH PRIVATE KEY-----
    

runcmd:
  # Host Key wurde geschrieben -> SSH neu starten, damit er aktiv wird
  - systemctl restart ssh
  - systemctl start nginx
  - systemctl enable nginx

users:
  - name: devops
    groups: sudo
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILIbSuHbd81jNJJVD9gBAfm3QuImCebO+v8eeG7rUC2v jeel-st