#cloud-config
package_update: true
package_upgrade: true

ssh_pwauth: false
disable_root: true

ssh_keys:
  ed25519_private: |
    ${tls_private_key}

write_files:
  - path: /etc/cloud/templates/hosts.debian.tmpl
    content: |
      127.0.1.1 {{fqdn}} {{hostname}}
      127.0.0.1 localhost
      
      10.0.1.10 gateway.${dnsDomainName} gateway
      10.0.1.20 intern.${dnsDomainName} intern

runcmd:
  # Host Key wurde geschrieben -> SSH neu starten, damit er aktiv wird
  - systemctl restart ssh
  - systemctl enable nginx
  - systemctl restart nginx

users:
  - name: ${loginUser}
    groups: sudo
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash
    ssh_authorized_keys:
      - ${sshKey}